language: java
jdk:
  - oraclejdk7

branches:
  only:
    - master

env:
  global:
  - secure: "fuzmYxrELKtca171eLuZhH9Q3f07lYQlcYa5Cjr3UKybKVS0yPz2AilB8J6Uq+jF0/tpvL/33rFe4wRKHfL7T1HPfgozSvXHUnTTmGpGe3/zI8YKx+e8n0v/Bo3lfYULvIhn8RnpjjTV2prntzMuijCnWP96r1C36XE0r6qWJ50="
  - secure: "noUDT4cCs75PcmdOl/sfVV/ky919as2ae6BgaE6adgwTwFU5/rmmpJpiFnnuwuf5xuTPCiVrWIjl24zE0DVBvrKdUCVkcyzV5xsmKQkDOlyDQ8PjLCEODdoQHriI+V2hpZFkzt08OlmKXy/9Z4nJ663Xw/z0Pp4oOrkwDnmv7Gs="
  - secure: "pJEqMlvtlzaXnmUj3BPZQai8oBNvXsN5AcXZbFzakgYvG1Z55p56Fer14QLd/2G+oW7DwT1EbJBwXqDblpsIYDZLQBdWd5VEpsgjchLpGD/vBajxlF41oleL7V0CRipxeysji6Nnusi5RWk9vYk1UZ2lLEvkay7Vb/3ACnXptXY="

script: mvn test jacoco:report coveralls:jacoco

after_success:
  - mvn clean deploy --settings settings.xml
